### ISSUE TITLE
Statystyki - wdrożenie

### ISSUE THREAD

**Issue by rantonczyk** [rantonczyk/NPG#24]
1. Zmiana statystyk: klasa ma przechowywać informacje o: liczbie gier, najlepszym wyniku, ilości zniszczonych dymków
2. Wdrożenie statystyk: na początku działania programu należy z pliku wczytać i utworzyć 3 obiekty klasy _stats_, po jednej na tryb trudności, a po zakończeniu działania programu zapisać je z powrotem do pliku

**Comment by mattt2137** [comment]
Dodałem zmienną `bubbles_destroyed` i funkcjonalność z zapisem do pliku.
